#!/bin/python3
# priority scheduling exercise
# Olivier Bonaventure, 2020

from inginious import input, feedback
import re
 
def removeSpaces(string):
    return re.sub('[\s+]', '', string)

def packet_error(str,correct):
    if (str[-1] != correct[-1]):
        return "The first packet is not the right one"
    n=1
    while n<len(correct) and str.endswith(correct[len(correct)-n:]) :
      n=n+1
    if n==2 :  
        return "Only the first packet of your answer is the right one."
    else:
        return "Only the first {} packets of your answer are the right ones.".format(n-1)  


    
#q1
ans1 = "JIHGFEDCBA"
def checkq1(str):

    response = ""
    grade = 0
    if len(str) != len(ans1):
        feedback.set_problem_result("failed", "q1")
        response += "Your answer does not contain the first ten packets.\n"
        feedback.set_problem_feedback(response, "q1")
        return 0
    
    if any(char.isdigit() for char in str):
        feedback.set_problem_result("failed", "q1")
        response += "Your answer is incorrect. You include a packet from the low priority queue while this is the lowest priority one and the high priority queue always contains packets. \n"
        feedback.set_problem_feedback(response, "q1")
        return 0

    
    if str == ans1:
        feedback.set_problem_result("success", "q1")
        response += "Correct\n"
        feedback.set_problem_feedback(response, "q1")
        return 100
    else :
        feedback.set_problem_result("failed", "q1")
        feedback.set_problem_feedback(packet_error(str,ans1),"q1")
        return 0
    
    
    return grade

#q2
ans2 = "EDCBAedcba"

def checkq2(str):

    response = ""
    grade = 0
    if len(str) != len(ans2) :
        feedback.set_problem_result("failed", "q2")
        response += "Your answer does not contain the first ten packets.\n"
        feedback.set_problem_feedback(response, "q2")
        return 0

    if str == ans2:
        feedback.set_problem_result("success", "q2")
        response += "Correct\n"
        feedback.set_problem_feedback(response, "q2")
        return 100
    else :
        feedback.set_problem_result("failed", "q2")
        feedback.set_problem_feedback(packet_error(str,ans2),"q2")
        return 0
    
    return grade


#q3
ans3 = "eEdDcCbBaA"

def checkq3(str):

    response = ""
    grade = 0
    if len(str) != len(ans3) :
        feedback.set_problem_result("failed", "q3")
        response += "Your answer does not contain the first ten packets.\n"
        feedback.set_problem_feedback(response, "q3")
        return 0

    if str == ans3:
        feedback.set_problem_result("success", "q3")
        response += "Correct\n"
        feedback.set_problem_feedback(response, "q3")
        return 100
    else :
        feedback.set_problem_result("failed", "q3")
        feedback.set_problem_feedback(packet_error(str,ans3),"q3")
        return 0
    
    return grade

#q4
ans4 = "0dEDCBAcba"

def checkq4(str):

    response = ""
    grade = 0
    if len(str) != len(ans4) :
        feedback.set_problem_result("failed", "q4")
        response += "Your answer does not contain the first ten packets.\n"
        feedback.set_problem_feedback(response, "q4")
        return 0

    if str == ans4:
        feedback.set_problem_result("success", "q4")
        response += "Correct\n"
        feedback.set_problem_feedback(response, "q4")
        return 100
    else :
        feedback.set_problem_result("failed", "q4")
        feedback.set_problem_feedback(packet_error(str,ans4),"q4")
        return 0
    
    return grade




grade=0
grade += checkq1(removeSpaces(input.get_input("q1")))/4
grade += checkq2(removeSpaces(input.get_input("q2")))/4
grade += checkq3(removeSpaces(input.get_input("q3")))/4
grade += checkq4(removeSpaces(input.get_input("q4")))/4

feedback.set_grade(grade)

if grade == 100:
    feedback.set_global_result("success")
else:
    feedback.set_global_result("failed")
# end
