#!/bin/python3

# Olivier Bonaventure, 2020

from inginious import input, feedback
import re
 
def removeSpaces(string):
    return re.sub('[\s+]', '', string)


#q1
ans1 = ".u.q.o.m.k.i.g.e.c.a"

def checkq1(str):

    response = ""
    errors = 0
    grade = 0
    if len(str) != len(ans1) :
        feedback.set_problem_result("failed", "q1")
        response += "Your answer does not contain the same number of characters as the ones in the question. Remember that you should replace the packets that are not accepted by the token bucket with a dot and leave the existing dots\n"
        feedback.set_problem_feedback(response, "q1")
        return 0

    if str == ans1:
        feedback.set_problem_result("success", "q1")
        response += "Correct\n"
        feedback.set_problem_feedback(response, "q1")
        return 100

    return grade

#q2
#
ans2 = "...q...m...i...e..ba"
def checkq2(str):

    response = ""
    errors = 0
    grade = 0
    if len(str) != len(ans2) :
        feedback.set_problem_result("failed", "q2")
        response += "Your answer does not contain the same number of characters as the ones in the question. Remember that you should replace the packets that are not accepted by the token bucket with a dot and leave the existing dots\n"
        feedback.set_problem_feedback(response, "q2")
        return 0

    if str == ans2:
        feedback.set_problem_result("success", "q2")
        response += "Correct\n"
        feedback.set_problem_feedback(response, "q2")
        return 100


    return grade

grade=0
grade += checkq1(removeSpaces(input.get_input("q1")))/2
grade += checkq2(removeSpaces(input.get_input("q2")))/2


feedback.set_grade(grade)

if grade == 100:
    feedback.set_global_result("success")
else:
    feedback.set_global_result("failed")
# end
